cd ~/go-ethereum
mkdir -p .github/workflows
nano .github/workflows/build.yml   # 
git add .github/workflows/build.yml
git commit -m "Add GitHub Actions workflow for building Geth"
git push origin master
